---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: immich
  namespace: apps
spec:
  chart: oci://ghcr.io/immich-app/immich-charts/immich
  failurePolicy: abort
  targetNamespace: apps
  createNamespace: false
  version: 0.13.1
  valuesContent: |-
    controllers:
      main:
        containers:
          main:
            securityContext:
              allowPrivilegeEscalation: false
            resources:
              limits:
                memory: 2Gi
              requests:
                memory: 128Mi
            env:
              DB_HOSTNAME: "immich-postgresql"
              DB_USERNAME: "postgres"
              DB_DATABASE_NAME: "immich"
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-db-credentials
                    key: password

    defaultPodOptions:
      securityContext:
        runAsUser: $MY_UID
        runAsGroup: $MY_UID
        fsGroup: $MY_UID

    server:
      controllers:
        main:
          containers:
            main:
              image:
                repository: ghcr.io/immich-app/immich-server
                tag: v3.0.3
              env:
                HWACCEL_VAAPI_ENABLED: "true"
      persistence:
        dri:
          type: hostPath
          hostPath: /dev/dri
          globalMounts:
            - path: /dev/dri
        external:
          existingClaim: immich-external-pvc
          globalMounts:
            - path: /external
              readOnly: true

    machine-learning:
      controllers:
        main:
          containers:
            main:
              image:
                repository: ghcr.io/immich-app/immich-machine-learning
                tag: release-rocm
      defaultPodOptions:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                    - key: has-amdgpu
                      operator: In
                      values:
                        - "true"
      persistence:
        kfd:
          type: hostPath
          hostPath: /dev/kfd
          globalMounts:
            - path: /dev/kfd
        dri:
          type: hostPath
          hostPath: /dev/dri
          globalMounts:
            - path: /dev/dri

    immich:
      persistence:
        library:
          existingClaim: immich-library-pvc

    valkey:
      enabled: true
