---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: immich-prod-tls
  namespace: apps
spec:
  secretName: immich-prod-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - immich.$SERVICES_DOMAIN
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich-ingress
  namespace: apps
spec:
  entryPoints:
    - websecure
    - websecure-proxy
  routes:
    - match: Host(`immich.$SERVICES_DOMAIN`)
      kind: Rule
      middlewares:
        - name: geoblock
          namespace: base
        - name: crowdsec-bouncer
          namespace: base
        - name: authelia-with-optional-header-gate
          namespace: base
      services:
        - name: immich-server
          port: 2283
  tls:
    secretName: immich-prod-tls

