---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: send
  namespace: apps
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: send
  template:
    metadata:
      labels:
        app: send
    spec:
      initContainers:
        - name: wait-for-redis
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              until nc -z send-redis 6379; do
                echo "Waiting for Redis..."
                sleep 1
              done
              echo "Redis is ready."
      securityContext:
        fsGroup: $MY_UID
      containers:
        - name: send
          image: registry.gitlab.com/timvisee/send:latest
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: "production"
            - name: BASE_URL
              value: "https://send.$SERVICES_DOMAIN"
            - name: PORT
              value: "80"
            - name: REDIS_HOST
              value: "send-redis.apps.svc.cluster.local"
            - name: REDIS_RETRY_TIME
              value: "86400000"
            - name: FILE_DIR
              value: "/uploads"
            - name: MAX_FILES_PER_ARCHIVE
              value: "512"
            - name: MAX_FILE_SIZE
              value: "137438953472"
            - name: MAX_EXPIRE_SECONDS
              value: "31536000"
            - name: MAX_DOWNLOADS
              value: "1000000000"
            - name: DOWNLOAD_COUNTS
              value: "10,1,2,5,10,15,25,50,100,1000,1000000000"
            - name: EXPIRE_TIMES_SECONDS
              value: "3600,86400,604800,2592000,31536000"
            - name: DEFAULT_DOWNLOADS
              value: "100"
            - name: DEFAULT_EXPIRE_SECONDS
              value: "2592000"
          volumeMounts:
            - name: uploads
              mountPath: /uploads
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 128Mi
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: send-uploads
---
apiVersion: v1
kind: Service
metadata:
  name: send
  namespace: apps
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: send
