---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-openwebui-ollama-ingress
  namespace: apps
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: ollama
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: open-webui
      ports:
        - port: 11434
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-openwebui-redis-ingress
  namespace: apps
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: open-webui-redis
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: open-webui
      ports:
        - port: 6379
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ollama-egress
  namespace: apps
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: ollama
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 443
  policyTypes:
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-openwebui-egress
  namespace: apps
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: open-webui
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 443
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 80
  policyTypes:
    - Egress
