
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mdscl-camera-src-pv
spec:
  capacity:
    storage: 4000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  local:
    path: $MDSCL_DEVICE_SYNC_PATH/DCIM/Camera
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: hostpath-main
              operator: In
              values:
                - "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mdscl-camera-src-pvc
  namespace: syncthing
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 4000Gi
  volumeName: mdscl-camera-src-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mdscl-camera-dst-pv
spec:
  capacity:
    storage: 4000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  local:
    path: $MAIN_PARENT_DIR/Main/Media/Camera
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: hostpath-main
              operator: In
              values:
                - "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mdscl-camera-dst-pvc
  namespace: syncthing
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 4000Gi
  volumeName: mdscl-camera-dst-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mdscl-screenshots-src-pv
spec:
  capacity:
    storage: 4000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  local:
    path: $MDSCL_DEVICE_SYNC_PATH/Screenshots
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: hostpath-main
              operator: In
              values:
                - "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mdscl-screenshots-src-pvc
  namespace: syncthing
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 4000Gi
  volumeName: mdscl-screenshots-src-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mdscl-screenshots-dst-pv
spec:
  capacity:
    storage: 4000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  local:
    path: $MAIN_PARENT_DIR/Main/Media/Screenshots
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: hostpath-main
              operator: In
              values:
                - "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mdscl-screenshots-dst-pvc
  namespace: syncthing
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 4000Gi
  volumeName: mdscl-screenshots-dst-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mdscl-screenrecs-src-pv
spec:
  capacity:
    storage: 4000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  local:
    path: "$MDSCL_DEVICE_SYNC_PATH/Screen Recordings"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: hostpath-main
              operator: In
              values:
                - "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mdscl-screenrecs-src-pvc
  namespace: syncthing
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 4000Gi
  volumeName: mdscl-screenrecs-src-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mdscl-screenrecs-dst-pv
spec:
  capacity:
    storage: 4000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  local:
    path: $MAIN_PARENT_DIR/Main/Media/Recordings
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: hostpath-main
              operator: In
              values:
                - "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mdscl-screenrecs-dst-pvc
  namespace: syncthing
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 4000Gi
  volumeName: mdscl-screenrecs-dst-pv
---
apiVersion: v1
kind: Secret
metadata:
  name: mdscl-secret
  namespace: syncthing
type: Opaque
stringData:
  NTFY_SERVICE_USER_TOKEN: "$NTFY_SERVICE_USER_TOKEN"
