---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ollama
  namespace: apps
spec:
  chart: ollama
  repo: https://helm.otwld.com/
  targetNamespace: apps
  createNamespace: false
  failurePolicy: abort
  version: 1.70.0
  valuesContent: |-
    persistentVolume:
      enabled: true
      existingClaim: ollama-models-pvc
    ollama:
      gpu:
        enabled: $GPU_NODES_AVAILABLE
        type: amd
    resources:
      limits:
        memory: 2Gi
      requests:
        memory: 128Mi
    podSecurityContext:
      fsGroup: $MY_UID
      runAsUser: $MY_UID
      runAsGroup: $MY_UID
    containerSecurityContext:
      allowPrivilegeEscalation: false
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: has-amdgpu
                  operator: In
                  values:
                    - "true"
    tolerations:
      - key: scheduling-discouraged
        operator: Equal
        value: "true"
        effect: PreferNoSchedule
