---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ollama
  namespace: apps
spec:
  chart: ollama
  repo: https://helm.otwld.com/
  targetNamespace: apps
  createNamespace: false
  failurePolicy: abort
  version: 1.66.0
  valuesContent: |-
    persistentVolume:
      enabled: true
      existingClaim: ollama-models-pvc
    ollama:
      gpu:
        # Set enabled: true when an AMD GPU node is available
        enabled: false
        type: amd
    resources:
      limits:
        memory: 2Gi
      requests:
        memory: 128Mi
    podSecurityContext:
      fsGroup: $MY_UID
      runAsUser: $MY_UID
      runAsGroup: $MY_UID
    containerSecurityContext:
      allowPrivilegeEscalation: false
    # Uncomment when an AMD GPU node is available
    # affinity:
    #   nodeAffinity:
    #     preferredDuringSchedulingIgnoredDuringExecution:
    #       - weight: 100
    #         preference:
    #           matchExpressions:
    #             - key: has-amdgpu
    #               operator: In
    #               values:
    #                 - "true"
    # Uncomment when an AMD GPU node is available
    # tolerations:
    #   - key: scheduling-discouraged
    #     operator: Equal
    #     value: "true"
    #     effect: PreferNoSchedule
