---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ollama
  namespace: apps
spec:
  chart: ollama
  repo: https://helm.otwld.com/
  targetNamespace: apps
  createNamespace: false
  failurePolicy: abort
  version: 1.71.0
  valuesContent: |-
    image:
      tag: "0.32.4-rocm"
    volumes:
      - name: dev-kfd
        hostPath:
          path: /dev/kfd
          type: CharDevice
      - name: dev-dri
        hostPath:
          path: /dev/dri
    volumeMounts:
      - name: dev-kfd
        mountPath: /dev/kfd
      - name: dev-dri
        mountPath: /dev/dri
    securityContext:
      privileged: true
    persistentVolume:
      enabled: false
    ollama:
      mountPath: /.ollama
    resources:
      requests:
        memory: 2Gi
    podSecurityContext:
      fsGroup: $MY_UID
      runAsUser: $MY_UID
      runAsGroup: $MY_UID
    containerSecurityContext:
      allowPrivilegeEscalation: false
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: has-amdgpu
                  operator: In
                  values:
                    - "true"
    tolerations:
      - key: scheduling-discouraged
        operator: Equal
        value: "true"
        effect: PreferNoSchedule
    extraEnv:
      - name: OLLAMA_MODELS
        value: /.ollama
