apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-models-pv
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: ollama-models
    volumeAttributes:
      server: nfs-server.base.svc.cluster.local
      share: /k3s-state
      subDir: ollama-models
      mountOptions: nolock
      mountPermissions: "0755"
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: nfs
  volumeName: ollama-models-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openwebui-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: openwebui-data
    volumeAttributes:
      server: nfs-server.base.svc.cluster.local
      share: /k3s-state
      subDir: openwebui-data
      mountOptions: nolock
      mountPermissions: "0755"
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebui-data-pvc
  namespace: apps
  labels:
    auto-backup: "true"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs
  volumeName: openwebui-data-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: open-webui-pipelines-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: open-webui-pipelines
    volumeAttributes:
      server: nfs-server.base.svc.cluster.local
      share: /k3s-state
      subDir: open-webui-pipelines
      mountOptions: nolock
      mountPermissions: "0755"
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-pipelines
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs
  volumeName: open-webui-pipelines-pv
---
apiVersion: v1
kind: Secret
metadata:
  name: openwebui-oidc
  namespace: apps
type: Opaque
stringData:
  client-secret: "$AUTHELIA_OPENWEBUI_CLIENT_SECRET"
