---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik.yaml
  - middlewares.yaml
  - prereqs.yaml
configMapGenerator:
  - name: traefik-local-plugins
    namespace: kube-system
    files:
      - plugin.wasm
      - .traefik.yml
    options:
      disableNameSuffixHash: true
