apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: apps
  annotations:
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:33.0.3
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 80
          readinessProbe:
            tcpSocket:
              port: 80
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
            initialDelaySeconds: 15
          env:
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-admin-secret
                  key: NEXTCLOUD_ADMIN_USER
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-admin-secret
                  key: NEXTCLOUD_ADMIN_PASSWORD
            - name: SQLITE_DATABASE
              value: "nextcloud"
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: "nextcloud.$SERVICES_DOMAIN"
            - name: APACHE_DISABLE_REWRITE_IP
              value: "1"
            - name: TRUSTED_PROXIES
              value: "10.0.0.0/8"
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 128Mi
      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: nextcloud
  ports:
    - port: 80
      targetPort: 80
