apiVersion: v1
kind: PersistentVolume
metadata:
  name: dscpln-data-pv
spec:
  capacity:
    storage: 4096Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: dscpln-data
    volumeAttributes:
      server: nfs-server.base.svc.cluster.local
      share: /dscpln
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dscpln-data-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4096Gi
  storageClassName: nfs
  volumeName: dscpln-data-pv
---
apiVersion: v1
kind: Secret
metadata:
  name: dscpln-ntfy-token
  namespace: apps
type: Opaque
stringData:
  token: "$NTFY_WRITE_ONLY_ACCOUNT_TOKEN"

