apiVersion: v1
kind: PersistentVolume
metadata:
  name: dscpln-data-pv
spec:
  capacity:
    storage: 5Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  local:
    path: $DSCPLN_TRANSACTIONS_PATH
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: hostpath-main
              operator: In
              values:
                - "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dscpln-data-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath
  resources:
    requests:
      storage: 5Mi
  volumeName: dscpln-data-pv
---
apiVersion: v1
kind: Secret
metadata:
  name: dscpln-ntfy-token
  namespace: apps
type: Opaque
stringData:
  token: "$NTFY_WRITE_ONLY_ACCOUNT_TOKEN"
