apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-data-pvc
  namespace: apps
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-extensions-pvc
  namespace: apps
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: freshrss-secret
  namespace: apps
type: Opaque
stringData:
  FRESHRSS_ADMIN_PASSWORD: "$FRESHRSS_ADMIN_PASSWORD"
