x-logging: &logging
    options:
        max-size: 10m
        max-file: 5

services:

    # FRPC - Reverse Proxy Client
    frpc:
        image: fatedier/frpc:v0.68.1
        container_name: frpc
        restart: always
        volumes:
        - $STATE_DIR/frpc/frpc.toml:/frpc.toml
        network_mode: host
        labels:
        - "com.centurylinklabs.watchtower.enable=false"
        healthcheck:
            test: ["CMD-SHELL", "wget --no-verbose --tries=1 -O - http://127.0.0.1:7400/healthz || exit 1"]
            interval: 30s
            timeout: 10s
            start_period: 1m
            retries: 3
        logging: 
            options:
                max-size: 10m
                max-file: 5
        command: "-c /frpc.toml"