services:

    # FRPC - Reverse Proxy Client
    frpc:
        image: fatedier/frpc:v0.64.0
        container_name: frpc
        restart: always
        volumes:
        - $STATE_DIR/frpc/frpc.toml:/frpc.toml
        network_mode: host
        labels:
        - "com.centurylinklabs.watchtower.enable=false"
        logging: 
            options:
                max-size: 10m
                max-file: 5
        command: "-c /frpc.toml"