apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config-pvc
  namespace: apps
  labels:
    auto-backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-secret
  namespace: apps
type: Opaque
stringData:
  PROWLARR__AUTH__APIKEY: "$PROWLARR_API_KEY"
