---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: jellyfin
  namespace: apps
spec:
  chart: jellyfin
  repo: https://jellyfin.github.io/jellyfin-helm
  failurePolicy: abort
  targetNamespace: apps
  createNamespace: false
  version: 3.2.0
  valuesContent: |-
    persistence:
      config:
        existingClaim: jellyfin-config-pvc
      media:
        enabled: false

    volumes:
      - name: dri
        hostPath:
          path: /dev/dri
      - name: tv
        persistentVolumeClaim:
          claimName: jellyfin-tv-pvc
      - name: youtube
        persistentVolumeClaim:
          claimName: jellyfin-youtube-pvc
      - name: arrstack-media
        persistentVolumeClaim:
          claimName: arrstack-media-pvc

    volumeMounts:
      - name: dri
        mountPath: /dev/dri
      - name: tv
        mountPath: /media/TV
        readOnly: true
      - name: youtube
        mountPath: /media/YouTube
        readOnly: true
      - name: arrstack-media
        mountPath: /media/Arrstack
        readOnly: true

    resources:
      limits:
        memory: 2Gi
      requests:
        memory: 128Mi
    podSecurityContext:
      runAsUser: $MY_UID
      runAsGroup: $MY_UID
    containerSecurityContext:
      allowPrivilegeEscalation: false
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: has-amdgpu
                  operator: In
                  values:
                    - "true"
    tolerations:
      - key: scheduling-discouraged
        operator: Equal
        value: "true"
        effect: PreferNoSchedule
