apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: jellyfin-config
    volumeAttributes:
      server: nfs-server.base.svc.cluster.local
      share: /k3s-state/jellyfin-config
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
  namespace: apps
  labels:
    auto-backup: "true"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs
  volumeName: jellyfin-config-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-tv-pv
spec:
  capacity:
    storage: 4096Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: jellyfin-tv
    volumeAttributes:
      server: nfs-server.base.svc.cluster.local
      share: /jellyfin-tv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-tv-pvc
  namespace: apps
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  volumeName: jellyfin-tv-pv
  resources:
    requests:
      storage: 4096Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-youtube-pv
spec:
  capacity:
    storage: 4096Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: jellyfin-youtube
    volumeAttributes:
      server: nfs-server.base.svc.cluster.local
      share: /jellyfin-youtube
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-youtube-pvc
  namespace: apps
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  volumeName: jellyfin-youtube-pv
  resources:
    requests:
      storage: 4096Gi
