apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
  namespace: apps
  labels:
    auto-backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-tv-pv
spec:
  capacity:
    storage: 4096Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: jellyfin-tv
    volumeAttributes:
      server: nfs-server.base.svc.cluster.local
      share: /jellyfin-tv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-tv-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4096Gi
  storageClassName: nfs
  volumeName: jellyfin-tv-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-youtube-pv
spec:
  capacity:
    storage: 4096Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: jellyfin-youtube
    volumeAttributes:
      server: nfs-server.base.svc.cluster.local
      share: /jellyfin-youtube
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-youtube-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4096Gi
  storageClassName: nfs
  volumeName: jellyfin-youtube-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: arrstack-media-pv
spec:
  capacity:
    storage: 4096Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: arrstack-media
    volumeAttributes:
      server: nfs-server.base.svc.cluster.local
      share: /arrstack-media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arrstack-media-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4096Gi
  storageClassName: nfs
  volumeName: arrstack-media-pv
