---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-immich-db-ingress
  namespace: apps
spec:
  podSelector:
    matchLabels:
      app: immich-postgresql
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: immich
      ports:
        - port: 5432
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-immich-valkey-ingress
  namespace: apps
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: valkey
      app.kubernetes.io/instance: immich
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: immich
      ports:
        - port: 6379
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-immich-ml-ingress
  namespace: apps
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: machine-learning
      app.kubernetes.io/instance: immich
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: immich
      ports:
        - port: 3003
  policyTypes:
    - Ingress
