apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: csi-driver-nfs
  namespace: kube-system
spec:
  chart: csi-driver-nfs
  repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
  failurePolicy: abort
  targetNamespace: kube-system
  version: 4.13.4
  valuesContent: |-
    node:
      dnsPolicy: ClusterFirstWithHostNet
