---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-tls
  namespace: kube-system
spec:
  secretName: local-tls
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - "*.lan"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-tls
  namespace: apps
spec:
  secretName: local-tls
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - "*.lan"
