---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: base
spec:
  chart: cert-manager
  repo: https://charts.jetstack.io
  failurePolicy: abort
  targetNamespace: base
  createNamespace: false
  version: 1.21.0
  valuesContent: |-
    installCRDs: true
    resources:
      limits:
        memory: 2Gi
      requests:
        memory: 128Mi
