apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-config-pvc
  namespace: apps
  labels:
    auto-backup: "true"
  annotations:
    backup.atlas/exclude: "index-*.db index-v2"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
