apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-home-pv
spec:
  capacity:
    storage: 4096Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  local:
    path: $MAIN_PARENT_DIR
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: hostpath-main
              operator: In
              values:
                - "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-home-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 4096Gi
  volumeName: syncthing-home-pv
