---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing
  namespace: apps
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: syncthing
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      hostNetwork: true
      securityContext:
        runAsUser: $MY_UID
        runAsGroup: $MY_UID
      initContainers:
        - name: fix-perms
          image: busybox:1.37
          command: ["sh", "-c", "chown -R $MY_UID:$MY_UID /var/syncthing/config"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: syncthing-config
              mountPath: /var/syncthing/config
      containers:
        - name: syncthing
          image: syncthing/syncthing:2.1.2
          args:
            - "--home"
            - "/var/syncthing/config"
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: STGUIADDRESS
              value: "127.0.0.1:8384"
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 128Mi
          readinessProbe:
            tcpSocket:
              port: 22000
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: host-maindir-parent
              mountPath: /var/syncthing/hostmainparent
            - name: syncthing-config
              mountPath: /var/syncthing/config
      volumes:
        - name: host-maindir-parent
          persistentVolumeClaim:
            claimName: hostpath-main-node-main-parent-pvc
        - name: syncthing-config
          persistentVolumeClaim:
            claimName: syncthing-config-pvc
