---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-s3-ingress
  namespace: base
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: rustfs
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: base
      ports:
        - port: 9000
  policyTypes:
    - Ingress
