---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seerr-prod-tls
  namespace: apps
spec:
  secretName: seerr-prod-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - seerr.$SERVICES_DOMAIN
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: seerr-ingress
  namespace: apps
spec:
  entryPoints:
    - websecure
    - websecure-proxy
  routes:
    - match: Host(`seerr.$SERVICES_DOMAIN`)
      kind: Rule
      middlewares:
        - name: geoblock
          namespace: base
        - name: crowdsec-bouncer
          namespace: base
        - name: forwardauth-authelia
          namespace: base
      services:
        - name: seerr
          port: 80
  tls:
    secretName: seerr-prod-tls
