x-logging: &logging
    options:
        max-size: 10m
        max-file: 5

services:

    frpc:
        image: fatedier/frpc:v0.70.0
        container_name: frpc
        restart: always
        volumes:
          - $COMPOSE_STATE_DIR/frpc/frpc.toml:/frpc.toml
          - $COMPOSE_STATE_DIR/frpc/ca.crt:/etc/frp/ca.crt:ro
          - $COMPOSE_STATE_DIR/frpc/client.crt:/etc/frp/client.crt:ro
          - $COMPOSE_STATE_DIR/frpc/client.key:/etc/frp/client.key:ro
        network_mode: host
        healthcheck:
            test: ["CMD", "pgrep", "frpc"]
            interval: 30s
            timeout: 10s
            start_period: 1m
            retries: 3
        logging: *logging
        command: "-c /frpc.toml"
