---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: apps
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:latest@sha256:119aaa4a4f7349bcd2a136c5373a0d7925b5479915c7dfe0c0ad352db2a6d438
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 7878
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 128Mi
          readinessProbe:
            tcpSocket:
              port: 7878
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            - name: PUID
              value: "$MY_UID"
            - name: PGID
              value: "$MY_UID"
            - name: TZ
              value: "$TZ"
            - name: RADARR__AUTH__APIKEY
              valueFrom:
                secretKeyRef:
                  name: radarr-secret
                  key: RADARR__AUTH__APIKEY
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config-pvc
        - name: data
          persistentVolumeClaim:
            claimName: arrstack-media-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: radarr
  ports:
    - port: 7878
      targetPort: 7878
