---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-localhost-tls
  namespace: kube-system
spec:
  secretName: longhorn-localhost-tls
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - longhorn.localhost
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-prod-tls
  namespace: kube-system
spec:
  secretName: longhorn-prod-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - longhorn.$SERVICES_DOMAIN
