apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmchart.yaml
  - ingress.yaml
  - certificates.yaml # IGNORE INITIALLY
  - backup.yaml # IGNORE INITIALLY
  - network-policy.yaml # IGNORE INITIALLY
  - backup-labeler.yaml # IGNORE INITIALLY
