apiVersion: v1
kind: PersistentVolume
metadata:
  name: fmd-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: fmd
    volumeAttributes:
      server: nfs-server.base.svc.cluster.local
      share: /k3s-state
      subDir: fmd
      mountOptions: nolock
      mountPermissions: "0755"
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fmd-pvc
  namespace: apps
  labels:
    auto-backup: "true"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs
  volumeName: fmd-pv
---
apiVersion: v1
kind: Secret
metadata:
  name: fmd-secret
  namespace: apps
type: Opaque
stringData:
  FMD_REGISTRATIONTOKEN: "$FMD_REGISTRATIONTOKEN"
