apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fmd-pvc
  namespace: apps
spec:
  storageClassName: mayastor-install-single-replica
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: fmd-secret
  namespace: apps
type: Opaque
stringData:
  FMD_REGISTRATIONTOKEN: "$FMD_REGISTRATIONTOKEN"
