---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ntfy-prod-tls
  namespace: base
spec:
  secretName: ntfy-prod-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - ntfy.$SERVICES_DOMAIN
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ntfy-ingress
  namespace: base
spec:
  entryPoints:
    - websecure
    - websecure-proxy
  routes:
    - match: Host(`ntfy.$SERVICES_DOMAIN`)
      kind: Rule
      middlewares:
        - name: geoblock
          namespace: base
        - name: crowdsec-bouncer
          namespace: base
        - name: forwardauth-authelia
          namespace: base
      services:
        - name: ntfy
          port: 3000
  tls:
    secretName: ntfy-prod-tls

