apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-pvc
  namespace: base
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: ntfy-server-config
  namespace: base
type: Opaque
stringData:
  server.yml: |
    base-url: "https://ntfy.$SERVICES_DOMAIN"
    cache-file: "/home/ntfy/cache.db"
    attachment-cache-dir: "/home/ntfy/attachments"
    behind-proxy: true
    listen-http: ":3000"
