apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-pvc
  namespace: base
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: ntfy-server-config
  namespace: base
type: Opaque
stringData:
  server.yml: |
    base-url: "https://ntfy.$SERVICES_DOMAIN"
    cache-file: "/home/ntfy/cache.db"
    attachment-cache-dir: "/home/ntfy/attachments"
    behind-proxy: true
    listen-http: ":3000"

---
apiVersion: v1
kind: Secret
metadata:
  name: ntfy-auth
  namespace: base
type: Opaque
stringData:
  auth-users: "admin:$NTFY_ADMIN_PASSWORD_HASH:admin,service:$NTFY_WRITE_ONLY_ACCOUNT_PASSWORD_HASH:user"
  auth-tokens: "service:$NTFY_WRITE_ONLY_ACCOUNT_TOKEN"
  auth-access: "admin:*:read-write,service:*:write-only"
