---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: navidrome-prod-tls
  namespace: apps
spec:
  secretName: navidrome-prod-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - music.$SERVICES_DOMAIN
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: navidrome-ingress
  namespace: apps
spec:
  entryPoints:
    - websecure
    - websecure-proxy
  routes:
    - match: Host(`music.$SERVICES_DOMAIN`)
      kind: Rule
      middlewares:
        - name: geoblock
          namespace: base
        - name: crowdsec-bouncer
          namespace: base
        - name: authelia-with-optional-header-gate
          namespace: base
      services:
        - name: navidrome
          port: 4533
  tls:
    secretName: navidrome-prod-tls

