tcp:
  serversTransports:
    frps-proxy:
      proxyProtocol:
        version: 2
  routers:
    pc-https:
      rule: "HostSNI(`pc.$SERVICES_DOMAIN`) || HostSNI(`*.pc.$SERVICES_DOMAIN`)"
      entryPoints: [websecure]
      service: pc-https-frps
      tls:
        passthrough: true
  services:
    pc-https-frps:
      loadBalancer:
        serversTransport: frps-proxy
        servers:
          - address: "frps-with-multiuser:8443"
