{{- if .Values.apps.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prowlarr-prod-tls
  namespace: apps
spec:
  secretName: prowlarr-prod-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - prowlarr.$SERVICES_DOMAIN
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr-ingress
  namespace: apps
spec:
  entryPoints:
    - websecure
    - websecure-proxy
  routes:
    - match: Host(`prowlarr.$SERVICES_DOMAIN`)
      kind: Rule
      middlewares:
        - name: geoblock
          namespace: base
        - name: crowdsec-bouncer
          namespace: base
        - name: forwardauth-authelia
          namespace: base
      services:
        - name: prowlarr
          port: 9696
  tls:
    secretName: prowlarr-prod-tls
---
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-prowlarr-ingress
  namespace: apps
spec:
  podSelector:
    matchLabels:
      app: prowlarr
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: radarr
        - podSelector:
            matchLabels:
              app: sonarr
      ports:
        - port: 9696
  policyTypes:
    - Ingress
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config-pvc
  namespace: apps
  labels:
    auto-backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-secret
  namespace: apps
type: Opaque
stringData:
  PROWLARR__AUTH__APIKEY: "$PROWLARR_API_KEY"
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: apps
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:latest@sha256:91844fa2c927ad6ede5630127183cc7868b175f6223e83e6a5da1fffea2aa782
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 9696
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 128Mi
          readinessProbe:
            tcpSocket:
              port: 9696
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            - name: PUID
              value: "$MY_UID"
            - name: PGID
              value: "$MY_UID"
            - name: TZ
              value: "$TZ"
            - name: PROWLARR__AUTH__APIKEY
              valueFrom:
                secretKeyRef:
                  name: prowlarr-secret
                  key: PROWLARR__AUTH__APIKEY
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: prowlarr
  ports:
    - port: 9696
      targetPort: 9696
{{- end }}
