http:
  middlewares:
    authelia:
      forwardAuth:
        address: http://authelia:9091/api/verify?rd=https://auth.{{ CLOUD_SERVICES_DOMAIN }}/
        maxResponseBodySize: 1048576
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email
    geoblock:
      plugin:
        geoblock:
          silentStartUp: false
          allowLocalRequests: true
          logLocalRequests: false
          logAllowedRequests: true
          logApiRequests: true
          api: "https://get.geojs.io/v1/ip/country/{ip}"
          apiTimeoutMs: 750
          cacheSize: 15
          forceMonthlyUpdate: true
          allowUnknownCountries: false
          unknownCountryApiResponse: "nil"
          {{ GEOBLOCK_CONFIG_SUBSET }}
    crowdsec-bouncer:
      plugin:
        crowdsec-bouncer-traefik-plugin:
          enabled: true
          logLevel: INFO
          crowdsecMode: stream
          crowdsecLapiScheme: http
          crowdsecLapiHost: crowdsec:8080
          crowdsecLapiKey: {{ CROWDSEC_BOUNCER_KEY }}
          crowdsecappsecenabled: true
          crowdsecAppsecScheme: http
          crowdsecAppsecHost: crowdsec:7422
          crowdsecAppsecPath: "/"
          forwardedheaderstrustedips: "127.0.0.1/32"
  routers:
    http-to-frps:
      rule: "Host(`home.{{ BASE_SERVICES_DOMAIN }}`) || Host(`*.home.{{ BASE_SERVICES_DOMAIN }}`)"
      entryPoints: [web]
      service: http-frps
      priority: 100
  services:
    http-frps:
      loadBalancer:
        servers:
          - url: "http://frps:8080"

tcp:
  serversTransports:
    frps-proxy:
      proxyProtocol:
        version: 2
  routers:
    https-to-frps:
      rule: "HostSNI(`home.{{ BASE_SERVICES_DOMAIN }}`) || HostSNI(`*.home.{{ BASE_SERVICES_DOMAIN }}`)"
      entryPoints: [websecure]
      service: https-frps
      tls:
        passthrough: true
  services:
    https-frps:
      loadBalancer:
        serversTransport: frps-proxy
        servers:
          - address: "frps:8443"
