apiVersion: v1
kind: PersistentVolume
metadata:
  name: crowdsec-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: crowdsec
    volumeAttributes:
      server: nfs-server.base.svc.cluster.local
      share: /k3s-state
      subDir: crowdsec
      mountOptions: nolock
      mountPermissions: "0755"
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crowdsec-pvc
  namespace: base
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs
  volumeName: crowdsec-pv
---
apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-lapi-configs
  namespace: base
type: Opaque
stringData:
  http.yaml: |
    type: http
    name: http_default
    log_level: debug
    format: |
      {{.|toJson}}
    url: http://ntfy.base.svc.cluster.local:3000/${TARGET}_services_crowdsec
    method: POST
    headers:
      Authorization: Bearer $NTFY_WRITE_ONLY_ACCOUNT_TOKEN
      Title: CrowdSec on ${TARGET}
      Priority: min
  navidrome.whitelist.yaml: |
    name: imranr/navidrome
    description: "Whitelist for Navidrome"
    whitelist:
      reason: "Downloading from Navidrome using client apps can cause false positives"
      expression:
        - evt.Overflow.Alert.Events[0].GetMeta('target_fqdn') == 'music.$SERVICES_DOMAIN'
        - evt.Overflow.Alert.GetScenario() in ['crowdsecurity/http-probing', 'crowdsecurity/http-crawl-non_statics']
  immich.whitelist.yaml: |
    name: imranr/immich
    description: "Whitelist for Immich"
    whitelist:
      reason: "Browsing Immich can cause false positives"
      expression:
        - evt.Overflow.Alert.Events[0].GetMeta('target_fqdn') == 'immich.$SERVICES_DOMAIN'
        - evt.Overflow.Alert.GetScenario() in ['crowdsecurity/http-probing']
        - evt.Meta.http_verb == 'GET'
        - evt.Meta.http_status == '404'
        - evt.Meta.http_path matches '/api/assets/.+'
  homeassistant.whitelist.yaml: |
    name: imranr/homeassistant
    description: "Whitelist for HomeAssistant"
    whitelist:
      reason: "HomeAssistant webhooks can cause false positives"
      expression:
        - evt.Overflow.Alert.Events[0].GetMeta('target_fqdn') == 'ha.$SERVICES_DOMAIN'
        - evt.Overflow.Alert.GetScenario() in ['LePresidente/http-generic-403-bf']
        - evt.Meta.http_verb == 'POST'
        - evt.Meta.http_path matches '^/api/webhook/.+'
---
apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-secrets
  namespace: base
type: Opaque
stringData:
  bouncer-key: "$CROWDSEC_BOUNCER_KEY"

