#!/usr/bin/env python3
"""lib/vars_validator.py — validate a target's VARS file against its template.

Reads targets/<t>/VARS.template.env and the resolved real VARS file
(secrets/VARS.<t>.env -> secrets/VARS.env -> VARS.<t>.env -> VARS.env), then:
  - requires every template key to exist in the real file
  - rejects placeholder values (change_me / changeme / abc / REPLACE_ME / <...>)
  - expands ${NAME} references (strict: NAME must be defined earlier in-file;
    bare $ stays literal — no os.environ leakage)
and writes current_target/vars.yml (chmod 600): every resolved value as a
string, plus a top-level `_vars_keys` list. Ansible playbooks include it via
`include_vars` (keys become template variables; _vars_keys lets them rebuild
the dict for docker-compose environment interpolation).

Security: variable values never appear on argv or in stdout/stderr — errors
print variable names only.

Usage:
  lib/vars_validator.py <target>
"""

import os
import re
import sys

try:
    from dotenv import parser as _dotenv_parser
except ImportError:  # task prereqs (universal) must work before this is installed
    _dotenv_parser = None

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PLACEHOLDERS = ("change_me", "changeme", "abc", "REPLACE_ME")

_REF_RE = re.compile(r"\$\{(?P<name>[A-Za-z_][A-Za-z0-9_]*)(?::-(?P<default>[^}]*))?\}")


def die(msg):
    print(f"Error: {msg}", file=sys.stderr)
    sys.exit(1)


def resolve_vars_file(target):
    candidates = [
        os.path.join(ROOT, "secrets", f"VARS.{target}.env"),
        os.path.join(ROOT, "secrets", "VARS.env"),
        os.path.join(ROOT, f"VARS.{target}.env"),
        os.path.join(ROOT, "VARS.env"),
    ]
    for c in candidates:
        if os.path.isfile(c):
            return c
    return None


def parse_vars_file(path):
    """Parse a dotenv file -> (values: dict, keys-in-order). Hard-fails on
    syntax errors (python-dotenv silently skips malformed lines)."""
    if _dotenv_parser is None:
        die("python3-dotenv is not installed. Run: task prereqs")
    values = {}
    order = []
    with open(path, encoding="utf-8") as f:
        for binding in _dotenv_parser.parse_stream(f):
            if binding.error:
                die(f"{path}:{binding.original.line}: could not parse this line (unterminated quote?)")
            if binding.key is not None:
                values[binding.key] = binding.value
                order.append(binding.key)
    return values, order


def template_keys(target):
    tpl = os.path.join(ROOT, "targets", target, "VARS.template.env")
    if not os.path.isfile(tpl):
        return []
    values, _ = parse_vars_file(tpl)
    return list(values.keys())


def expand_value(value, varname, defined):
    """Expand ${NAME} using previously-defined keys only (bash source semantics
    minus os.environ). Unknown references are hard errors."""

    def _sub(m):
        name = m.group("name")
        if m.group("default") is not None:
            die(f"{varname} uses unsupported ${{{name}:-...}} default syntax")
        if name not in defined:
            die(f"{varname} references ${{{name}}} which is not defined earlier in the VARS file")
        return defined[name]

    return _REF_RE.sub(_sub, value)


def emit_yaml(path, values, order):
    import tempfile

    lines = ["# Generated by lib/vars_validator.py — do not edit.",
             f"_vars_keys: [ {', '.join(repr(k) for k in order)} ]"]
    for k in order:
        v = values[k]
        if "\n" in v:
            chomping = "|-" if not v.endswith("\n") else "|"
            body = v.split("\n")
            if v.endswith("\n"):
                body = body[:-1]
            lines.append(f"{k}: {chomping}")
            lines.extend(f"  {l}" for l in body)
        else:
            lines.append(f"{k}: {v!r}")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(path), prefix=".vars.yml.")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")
        os.chmod(tmp, 0o600)
        os.replace(tmp, path)
    except BaseException:
        os.unlink(tmp)
        raise


def main(argv):
    if len(argv) != 1:
        print("Usage: lib/vars_validator.py <target>", file=sys.stderr)
        return 1
    target = argv[0]

    vars_file = resolve_vars_file(target)
    if vars_file is None:
        die(f"no VARS file found for target '{target}'")

    values, order = parse_vars_file(vars_file)
    tpl_keys = template_keys(target)

    missing = [k for k in tpl_keys if k not in values or values[k] is None]
    if missing:
        for k in missing:
            print(f"Error: {vars_file} is missing required variable: {k}", file=sys.stderr)
        return 1

    defined = {}
    for k in order:
        values[k] = expand_value(values[k], k, defined)
        defined[k] = values[k]

    for k in tpl_keys:
        v = (values.get(k) or "").strip()
        if v in PLACEHOLDERS or (v.startswith("<") and v.endswith(">")):
            print(f"Error: {vars_file} exports {k} with a placeholder value — replace it with a real value",
                  file=sys.stderr)
            return 1

    emit_yaml(os.path.join(ROOT, "current_target", "vars.yml"), values, order)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
