---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-org
  namespace: traefik
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "traefik"
spec:
  secretName: example-org-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.example.org"
  dnsNames:
  - "example.org"
  - "*.example.org"
  - "*.staging.example.org"