---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: homeassistant
  namespace: apps
spec:
  chart: home-assistant
  repo: https://blog.pavelsklenar.com/home-assistant-helm-chart/
  targetNamespace: apps
  createNamespace: false
  failurePolicy: abort
  version: 0.3.70
  valuesContent: |-
    deploymentStrategy: Recreate
    controller:
      type: Deployment
    image:
      tag: stable
    podSecurityContext: {}
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    securityContext:
      privileged: true
    persistence:
      enabled: true
      existingClaim: homeassistant-config-pvc
    ingress:
      external: true
    configuration:
      enabled: true
      forceInit: true
      trusted_proxies:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
    additionalVolumes:
      - name: usb-serial
        hostPath:
          path: /dev/serial/by-id
          type: DirectoryOrCreate
      - name: dbus
        hostPath:
          path: /run/dbus/system_bus_socket
          type: Socket
    additionalMounts:
      - name: usb-serial
        mountPath: /dev/serial/by-id
        readOnly: true
      - name: dbus
        mountPath: /run/dbus/system_bus_socket
    resources:
      limits:
        memory: 2Gi
      requests:
        memory: 128Mi
