---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homeassistant-prod-tls
  namespace: apps
spec:
  secretName: homeassistant-prod-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - ha.$SERVICES_DOMAIN
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homeassistant-ingress
  namespace: apps
spec:
  entryPoints:
    - websecure
    - websecure-proxy
  routes:
    - match: Host(`ha.$SERVICES_DOMAIN`) && PathPrefix(`/api/onboarding/backup`)
      kind: Rule
      middlewares:
        - name: geoblock
          namespace: base
        - name: crowdsec-bouncer
          namespace: base
      services:
        - name: homeassistant-home-assistant
          port: 8080
    - match: Host(`ha.$SERVICES_DOMAIN`)
      kind: Rule
      middlewares:
        - name: geoblock
          namespace: base
        - name: crowdsec-bouncer
          namespace: base
        - name: forwardauth-authelia
          namespace: base
      services:
        - name: homeassistant-home-assistant
          port: 8080
  tls:
    secretName: homeassistant-prod-tls
