apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-config-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: homeassistant-config
    volumeAttributes:
      server: nfs-server.base.svc.cluster.local
      share: /k3s-state/homeassistant-config
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config-pvc
  namespace: apps
  labels:
    auto-backup: "true"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs
  volumeName: homeassistant-config-pv