apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chibisafe-uploads-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chibisafe-db-pvc
  namespace: apps
  labels:
    auto-backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chibisafe-logs-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chibisafe-caddyfile
  namespace: apps
data:
  Caddyfile: |
    :80 {
      route {
        file_server * {
          root /app/uploads
          pass_thru
        }
        @api path /api/*
        reverse_proxy @api http://localhost:8000 {
          header_up Host {http.reverse_proxy.upstream.hostport}
          header_up X-Real-IP {http.request.header.X-Real-IP}
        }
        @docs path /docs*
        reverse_proxy @docs http://localhost:8000 {
          header_up Host {http.reverse_proxy.upstream.hostport}
          header_up X-Real-IP {http.request.header.X-Real-IP}
        }
        reverse_proxy http://localhost:8001 {
          header_up Host {http.reverse_proxy.upstream.hostport}
          header_up X-Real-IP {http.request.header.X-Real-IP}
        }
      }
    }
