x-logging: &logging
    options:
        max-size: 10m
        max-file: 5

services:

    dockerproxy:
        image: wollomatic/socket-proxy:1
        container_name: dockerproxy
        restart: unless-stopped
        read_only: true
        mem_limit: 64M
        cap_drop:
            - ALL
        security_opt:
            - no-new-privileges
        user: "65534:$DOCKER_GID"
        command:
            - "-loglevel=info"
            - '-allowGET=(/v1\..{1,2})?/(version|containers/.*|events)'
            - "-allowHEAD=/_ping"
            - "-proxysocketendpoint=/socket/docker.sock"
            - "-proxysocketendpointfilemode=0600"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - dockerproxy:/socket/
        logging: *logging

    traefik:
        image: traefik:v3
        container_name: traefik
        depends_on:
            - dockerproxy
        command:
            - "--global.sendAnonymousUsage=false"
            - "--log.level=INFO"
            - "--accesslog=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedByDefault=false"
            - "--entryPoints.web=true"
            - "--entryPoints.web.address=:80"
            - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
            - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
            - "--entryPoints.web.http.redirections.entryPoint.permanent=true"
            - "--entryPoints.websecure=true"
            - "--entryPoints.websecure.address=:443"
            - "--entryPoints.rtmp=true"
            - "--entryPoints.rtmp.address=:1935"
            - "--certificatesresolvers.le.acme.email=$DOMAIN_OWNER_EMAIL"
            - "--certificatesresolvers.le.acme.storage=/acme/acme.json"
            - "--certificatesresolvers.le.acme.tlschallenge=true"
            - "--providers.docker.endpoint=unix:///socket/docker.sock"
            - "--providers.docker.network=traefik"
        ports:
            - "443:443"
            - "1935:1935"
        volumes:
            - dockerproxy:/socket/:ro
            - $COMPOSE_STATE_DIR/traefik/acme:/acme
        networks:
            - traefik
        restart: unless-stopped
        mem_limit: 512M
        logging: *logging

    frpc:
        image: fatedier/frpc:v0.69.0
        container_name: frpc
        restart: always
        volumes:
            - $COMPOSE_STATE_DIR/frpc/frpc.toml:/frpc.toml
        network_mode: host
        logging: *logging
        command: "-c /frpc.toml"

    owncast:
        image: owncast/owncast:latest
        container_name: owncast
        restart: unless-stopped
        mem_limit: 2G
        depends_on:
            - traefik
        volumes:
            - $COMPOSE_STATE_DIR/owncast:/app/data
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.owncast.rule=Host(`owncast.$SERVICES_DOMAIN`)"
            - "traefik.http.routers.owncast.entrypoints=websecure"
            - "traefik.http.routers.owncast.tls.certresolver=le"
            - "traefik.http.routers.owncast.tls=true"
            - "traefik.http.services.owncast.loadbalancer.server.port=8080"
            - "traefik.tcp.routers.owncast-rtmp.rule=HostSNI(`owncast.$SERVICES_DOMAIN`)"
            - "traefik.tcp.routers.owncast-rtmp.entrypoints=rtmp"
            - "traefik.tcp.routers.owncast-rtmp.service=owncast-rtmp"
            - "traefik.tcp.routers.owncast-rtmp.tls=true"
            - "traefik.tcp.routers.owncast-rtmp.tls.certresolver=le"
            - "traefik.tcp.services.owncast-rtmp.loadbalancer.server.port=1935"
        networks:
            - traefik
        logging: *logging

networks:
    traefik:
        name: traefik
        ipam:
            config:
                - subnet: 172.19.0.0/24

volumes:
    dockerproxy:
        driver: local
        driver_opts:
            type: tmpfs
            device: tmpfs
            o: size=1k,uid=65534,gid=0,mode=0700,noexec
