x-logging: &logging
    options:
        max-size: 10m
        max-file: 5
services:

    frps-with-multiuser:
        image: imranrdev/frps-with-multiuser:latest
        container_name: frps-with-multiuser
        restart: always
        volumes:
          - $STATE_DIR/frps/tokens.txt:/workdir/service-data/frps-tokens.txt:ro
        network_mode: host
        healthcheck:
            test: ["CMD-SHELL", "wget --no-verbose --tries=1 -O - http://127.0.0.1:7500/healthz || exit 1"]
            interval: 30s
            timeout: 10s
            start_period: 1m
            retries: 3
        logging: *logging

    logtfy:
        image: imranrdev/logtfy:latest
        container_name: logtfy
        hostname: $TARGET
        restart: unless-stopped
        mem_limit: 256M
        volumes:
          - $STATE_DIR/logtfy/config.json:/logtfy/config.json:ro
          - /var/log/journal:/var/log/journal:ro
        logging: *logging

