#!/bin/bash
# DESC: Install system prerequisites on THIS machine: packages, the pinned helm
# binary, Docker (official bootstrap), and the machine-fact .env + host bind
# dirs for the local compose target (hostname == target). Idempotent — re-run
# after repo changes that add compose bind dirs.
set -euo pipefail

if [ -z "${INFRA_ROOT:-}" ]; then
    INFRA_ROOT="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/.." && pwd)"
    export INFRA_ROOT
fi
source "$INFRA_ROOT/scripts/common.sh"
set_my_uid

SU="$(get_sudo_cmd)"
HELM_VERSION="3.17.3"

usage() {
    echo "Usage: $(basename "$0")"
    echo
    echo "Machine-local (no target): installs packages, helm, Docker, then prepares"
    echo "the compose state for this machine's target (hostname-matched): machine-fact"
    echo ".env, host bind dirs owned by \$MY_UID, and the traefik acme.json seed."
    exit 1
}

[ $# -ge 1 ] && { [ "$1" = "-h" ] || [ "$1" = "--help" ]; } && usage

if command -v dnf >/dev/null 2>&1; then
    PKG_CMD=(dnf install -y)
    PACKAGES=(yq jq curl python3 golang openssl shellcheck yamllint git)
elif command -v apt-get >/dev/null 2>&1; then
    $SU apt-get update -y
    PKG_CMD=(apt-get install -y)
    PACKAGES=(yq jq curl python3 golang-go openssl shellcheck yamllint git)
else
    echo "Error: neither dnf nor apt-get found — cannot install packages" >&2
    exit 1
fi

echo "==> Installing packages"
$SU "${PKG_CMD[@]}" "${PACKAGES[@]}"

if [ ! -x /usr/local/bin/helm ]; then
    echo "==> Installing helm v$HELM_VERSION"
    case "$(uname -m)" in
        aarch64) arch=arm64 ;;
        *) arch=amd64 ;;
    esac
    curl -fsSL "https://get.helm.sh/helm-v${HELM_VERSION}-linux-${arch}.tar.gz" -o /tmp/helm.tar.gz
    tar -xzf /tmp/helm.tar.gz -C /tmp
    $SU install -m 0755 "/tmp/linux-${arch}/helm" /usr/local/bin/helm
    rm -rf /tmp/helm.tar.gz "/tmp/linux-${arch}"
fi

if ! command -v docker >/dev/null 2>&1 || ! docker compose version >/dev/null 2>&1; then
    echo "==> Installing Docker (official bootstrap)"
    curl -fsSL --connect-timeout 30 --max-time 300 https://get.docker.com -o /tmp/get-docker.sh
    $SU sh /tmp/get-docker.sh
    rm -f /tmp/get-docker.sh
fi
$SU systemctl enable --now docker

# ---- Local compose target prep (hostname-matched target only) ---------------
local_target="$(hostname)"
target_dir="$INFRA_ROOT/targets/$local_target"

if [ -d "$target_dir/compose" ] && [ -f "$target_dir/compose/compose.yaml" ]; then
    compose_files=(-f "$target_dir/compose/compose.yaml")
    [ -f "$target_dir/compose/compose.private.yaml" ] && compose_files+=(-f "$target_dir/compose/compose.private.yaml")

    env_args=()
    # The machine-fact .env (uid/gid/user) is written for EVERY target —
    # config envs never carry per-machine facts. Regenerated on every run so
    # uid/gid changes are picked up. MY_UID comes from set_my_uid (current UID,
    # forced 1000 when running as root — containers must not run as 0).
    docker_gid="$(getent group docker | cut -d: -f3)"
    {
        echo "# Machine facts — generated by scripts/prereqs.sh (re-run after uid/gid changes)."
        echo "MY_UID=$MY_UID"
        echo "DOCKER_GID=$docker_gid"
        echo "USER=$USER"
    } >"$target_dir/compose/.env"
    chmod 600 "$target_dir/compose/.env"
    echo "==> Wrote machine-fact env: $target_dir/compose/.env"
    env_args+=(--env-file "$target_dir/compose/.env")
    # VARS-driven targets take the shared config env too (later file wins —
    # facts would override any collision, which is the point).
    [ -f "$INFRA_ROOT/config/$local_target/compose.env" ] && env_args=(--env-file "$INFRA_ROOT/config/$local_target/compose.env" "${env_args[@]}")

    echo "==> Resolving compose host bind dirs"
    # Host bind dirs come from `docker compose config` itself (the interpolated,
    # resolved output) — the compose file is the single source of truth. Docker
    # would create missing dirs as root; creating them here keeps them writable
    # by containers running as $MY_UID.
    bind_dirs=$(
        docker compose -p "$local_target" "${compose_files[@]}" "${env_args[@]}" \
            config --format yaml 2>/dev/null |
            yq -r '.services[] | select(.volumes) | .volumes[] | (.source? // .) | split(":") | .[0]' |
            grep -F "$COMPOSE_STATE_DIR/" || true
    )
    sort -u <<<"$bind_dirs" | while read -r d; do
        [ -n "$d" ] || continue
        # A dot in the final path component means a file bind — create its parent.
        [[ "${d##*/}" == *.* ]] && d="${d%/*}"
        $SU mkdir -p "$d"
        $SU chown "${MY_UID}:${MY_UID}" "$d"
    done

    # Secret files the compose stack mounts from config/ must be readable by
    # containers running as $MY_UID (they are 0600 on the host).
    sed -n 's/^[[:space:]]*-[[:space:]]*\(\.\.\/\.\.\/\.\.\/config\/[A-Za-z0-9_.\/-]*\).*/\1/p' "$target_dir/compose/compose.yaml" |
        while read -r src; do
            [ -n "$src" ] || continue
            [ -f "$target_dir/compose/$src" ] && $SU chown "${MY_UID}:${MY_UID}" "$target_dir/compose/$src"
        done

    if grep -q 'traefik/acme' "$target_dir/compose/compose.yaml"; then
        acme_dir="$COMPOSE_STATE_DIR/traefik"
        $SU mkdir -p "$acme_dir"
        if [ ! -f "$acme_dir/acme.json" ]; then
            $SU bash -c "printf '{}' > '$acme_dir/acme.json'"
            $SU chown "${MY_UID}:${MY_UID}" "$acme_dir/acme.json"
            $SU chmod 600 "$acme_dir/acme.json"
            echo "==> Seeded $acme_dir/acme.json"
        fi
    fi
fi

echo "==> Verifying prerequisites"
missing=0
for tool in helm docker yq jq curl python3 go openssl shellcheck yamllint; do
    if command -v "$tool" >/dev/null 2>&1; then
        echo "  [OK] $tool"
    else
        echo "  [MISSING] $tool"
        missing=1
    fi
done
if docker compose version >/dev/null 2>&1; then
    echo "  [OK] docker compose"
else
    echo "  [MISSING] docker compose"
    missing=1
fi
exit $missing
