#!/bin/bash
# DESC: Generate the public-exposure (WireGuard) keys and render the tunnel
# configs into config/ (gitignored). Idempotent: existing keys are kept unless
# --force is given (--force invalidates every client profile). Writes the vps0
# hub conf under config/vps0/public-exposure/ (copy it to vps0), the srv0 host
# and preboot material under config/srv0/public-exposure/, and the qBittorrent
# keys into config/srv0/values.yaml. Never prints private keys. Run on srv0.
set -euo pipefail

if [ -z "${INFRA_ROOT:-}" ]; then
    INFRA_ROOT="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/.." && pwd)"
    export INFRA_ROOT
fi
source "$INFRA_ROOT/scripts/common.sh"

usage() {
    echo "Usage: $(basename "$0") [--force]"
    echo
    echo "  --force  regenerate every key (invalidates all public-exposure clients)"
    exit 1
}

force=false
case "${1:-}" in
    "") ;;
    --force) force=true ;;
    -h | --help) usage ;;
    *) usage ;;
esac

command -v wg >/dev/null 2>&1 ||
    { echo "Error: wg not found — install wireguard-tools (dnf install wireguard-tools)" >&2; exit 1; }
command -v yq >/dev/null 2>&1 ||
    { echo "Error: yq not found (see Prerequisites in AGENTS.md)" >&2; exit 1; }

srv0_env="$INFRA_ROOT/config/srv0/compose.env"
srv0_vals="$INFRA_ROOT/config/srv0/values.yaml"
server_dir="$INFRA_ROOT/config/vps0/public-exposure"
srv0_dir="$INFRA_ROOT/config/srv0/public-exposure"

[ -f "$srv0_env" ] || { echo "Error: $srv0_env not found (copy config_template first)" >&2; exit 1; }
[ -f "$srv0_vals" ] || { echo "Error: $srv0_vals not found (copy config_template first)" >&2; exit 1; }

# Migrate the pre-public-exposure FRP keys without touching their values.
if grep -q '^PROXY_HOST=' "$srv0_env" && ! grep -q '^PUBLIC_EXPOSURE_HOST=' "$srv0_env"; then
    sed -i 's/^PROXY_HOST=/PUBLIC_EXPOSURE_HOST=/' "$srv0_env"
    echo "migrated config/srv0/compose.env: PROXY_HOST -> PUBLIC_EXPOSURE_HOST"
fi
if grep -q '^TLS_SERVER_NAME=' "$srv0_env"; then
    sed -i 's/^TLS_SERVER_NAME=.*/PUBLIC_EXPOSURE_PORT=51822/' "$srv0_env"
    echo "migrated config/srv0/compose.env: TLS_SERVER_NAME -> PUBLIC_EXPOSURE_PORT"
fi

host=$(grep -E '^PUBLIC_EXPOSURE_HOST=' "$srv0_env" | head -1 | cut -d= -f2- | tr -d '"'"'"' ')
port=$(grep -E '^PUBLIC_EXPOSURE_PORT=' "$srv0_env" | head -1 | cut -d= -f2- | tr -d '"'"'"' ')
port="${port:-51822}"
[ -n "$host" ] || { echo "Error: PUBLIC_EXPOSURE_HOST must be set in $srv0_env" >&2; exit 1; }

host_ip=$(getent hosts "$host" | awk '{print $1; exit}')
[ -n "$host_ip" ] || { echo "Error: cannot resolve PUBLIC_EXPOSURE_HOST '$host'" >&2; exit 1; }

umask 077
mkdir -p "$server_dir" "$srv0_dir"

gen_keyfile() { # gen_keyfile <path.key> — creates the key + .pub unless kept
    local key="$1" pub="${1%.key}.pub"
    if [ -s "$key" ] && ! $force; then
        [ -s "$pub" ] || wg pubkey <"$key" >"$pub"
        return 0
    fi
    wg genkey >"$key"
    wg pubkey <"$key" >"$pub"
}

$force && echo "WARNING: --force — all existing public-exposure client profiles stop working"

gen_keyfile "$server_dir/server.key"  # public-exposure-server-wg
gen_keyfile "$srv0_dir/client.key"    # public-exposure-client-wg (srv0 host)
gen_keyfile "$srv0_dir/qbt.key"       # qbittorrent-wg (pod)
gen_keyfile "$srv0_dir/pre0.key"      # public-exposure-preboot-client-wg
cp "$server_dir/server.pub" "$srv0_dir/server.pub"

{
    echo "# public-exposure-server-wg hub (vps0). Generated by scripts/public-exposure-keygen.sh."
    echo "[Interface]"
    echo "Address = 10.99.0.1/32"
    echo "ListenPort = $port"
    echo "MTU = 1340"
    echo "PrivateKey = $(<"$server_dir/server.key")"
    echo
    echo "[Peer]"
    echo "# public-exposure-client-wg (srv0 host)"
    echo "PublicKey = $(<"$srv0_dir/client.pub")"
    echo "AllowedIPs = 10.99.0.2/32"
    echo
    echo "[Peer]"
    echo "# qbittorrent-wg (pod sidecar)"
    echo "PublicKey = $(<"$srv0_dir/qbt.pub")"
    echo "AllowedIPs = 10.99.0.3/32"
    echo
    echo "[Peer]"
    echo "# public-exposure-preboot-client-wg (initramfs)"
    echo "PublicKey = $(<"$srv0_dir/pre0.pub")"
    echo "AllowedIPs = 10.99.0.4/32"
} >"$server_dir/pubexp-server0.conf"

{
    echo "# public-exposure-client-wg (srv0 host). Generated by scripts/public-exposure-keygen.sh."
    echo "[Interface]"
    echo "PrivateKey = $(<"$srv0_dir/client.key")"
    echo "Address = 10.99.0.2/32"
    echo "MTU = 1340"
    echo
    echo "[Peer]"
    echo "PublicKey = $(<"$server_dir/server.pub")"
    echo "AllowedIPs = 10.99.0.1/32"
    echo "Endpoint = $host_ip:$port"
    echo "PersistentKeepalive = 25"
} >"$srv0_dir/pubexp-client0.conf"

QB_K="$(<"$srv0_dir/qbt.key")" \
    QB_PUB="$(<"$server_dir/server.pub")" \
    QB_EP="$host_ip:$port" \
    QB_IP="$host_ip" \
    yq -i '
        .QBITTORRENT_WG_PRIVATE_KEY = strenv(QB_K) |
        .QBITTORRENT_WG_PEER_PUBLIC_KEY = strenv(QB_PUB) |
        .QBITTORRENT_WG_ENDPOINT = strenv(QB_EP) |
        .QBITTORRENT_WG_ENDPOINT_IP = strenv(QB_IP)
    ' "$srv0_vals"

echo "public-exposure keys ready:"
echo "  hub conf (copy to vps0): config/vps0/public-exposure/pubexp-server0.conf"
echo "  srv0 host conf:          config/srv0/public-exposure/pubexp-client0.conf"
echo "  preboot material:        config/srv0/public-exposure/pre0.key (+ server.pub)"
echo "  qBittorrent keys:        written to config/srv0/values.yaml"
