serverAddr = "$PROXY_HOST"
serverPort = 7000
auth.additionalScopes = ["HeartBeats", "NewWorkConns"]
user = "$MAIN_NODE_HOSTNAME_LOWERCASE"
metadatas.token = "put_token_here"

[[proxies]]
name = "ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 8888
transport.useEncryption = true

[[proxies]]
name = "http"
type = "tcp"
localIP = "127.0.0.1"
localPort = 80
remotePort = 80
transport.proxyProtocolVersion = "v2"
transport.useEncryption = true

[[proxies]]
name = "https"
type = "tcp"
localIP = "127.0.0.1"
localPort = 443
remotePort = 443
transport.proxyProtocolVersion = "v2"
transport.useEncryption = true

[[proxies]]
name = "p2p"
type = "tcp"
localIP = "127.0.0.1"
localPort = 18080
remotePort = 18080
transport.useEncryption = true

[[proxies]]
name = "rpc"
type = "tcp"
localIP = "127.0.0.1"
localPort = 18089
remotePort = 18089
transport.useEncryption = true

[[proxies]]
name = "jitsi-udp"
type = "udp"
localIP = "127.0.0.1"
localPort = 10000
remotePort = 10000
transport.proxyProtocolVersion = "v2"
transport.useEncryption = true