apiVersion: v1
kind: PersistentVolume
metadata:
  name: opodsync-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: opodsync
    volumeAttributes:
      server: nfs-server.base.svc.cluster.local
      share: /k3s-state
      subDir: opodsync
      mountOptions: nolock
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opodsync-pvc
  namespace: apps
  labels:
    auto-backup: "true"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs
  volumeName: opodsync-pv

