apiVersion: v1
kind: PersistentVolume
metadata:
  name: logtfy-journal-pv
spec:
  capacity:
    storage: 4000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  local:
    path: /var/log/journal
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: hostpath-main
              operator: In
              values:
                - "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logtfy-journal-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 4000Gi
  volumeName: logtfy-journal-pv
