---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nfs-etab
  namespace: base
data:
  etab: |
    /exports *(rw,fsid=0,crossmnt,no_subtree_check,insecure,root_squash)
    /exports/music *(ro,fsid=1,no_subtree_check,insecure,root_squash)
    /exports/jellyfin-tv *(ro,fsid=2,no_subtree_check,insecure,root_squash)
    /exports/jellyfin-youtube *(ro,fsid=3,no_subtree_check,insecure,root_squash)
    /exports/arrstack-media *(rw,fsid=4,no_subtree_check,insecure,no_root_squash)
    /exports/frigate *(rw,fsid=6,no_subtree_check,insecure,no_root_squash)
    /exports/backups *(rw,fsid=5,no_subtree_check,insecure,no_root_squash)
