apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: mayastor-install
  namespace: kube-system
spec:
  chart: mayastor
  repo: https://openebs.github.io/mayastor-extensions
  failurePolicy: abort
  targetNamespace: openebs
  createNamespace: true
  version: 2.11.1
  valuesContent: |-
    base:
      default_req_timeout: 300s
    io_engine:
      cpuCount: "1"
      interruptMode:
        enabled: true
        nvmeIoQueuePollPeriod: "1000us"
      envcontext: "iova-mode=pa"
    etcd:
      replicaCount: 1
    loki:
      enabled: false
    nats:
      cluster:
        replicas: 1
    obs:
      callhome:
        enabled: false
    agents:
      ha:
        enabled: false
    csi:
      node:
        kubeletDir: /var/lib/kubelet
