apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gokapi-data
  namespace: apps
spec:
  storageClassName: mayastor-install-single-replica
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gokapi-config
  namespace: apps
  labels:
    auto-backup: "true"
spec:
  storageClassName: mayastor-install-single-replica
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
