---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openwebui-prod-tls
  namespace: apps
spec:
  secretName: openwebui-prod-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - gpt.$SERVICES_DOMAIN
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openwebui-ingress
  namespace: apps
spec:
  entryPoints:
    - websecure
    - websecure-proxy
  routes:
    - match: Host(`gpt.$SERVICES_DOMAIN`)
      kind: Rule
      middlewares:
        - name: geoblock
          namespace: base
        - name: crowdsec-bouncer
          namespace: base
      services:
        - name: open-webui
          port: 80
  tls:
    secretName: openwebui-prod-tls
