---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-openwebui-redis-ingress
  namespace: apps
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: open-webui-redis
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: open-webui
      ports:
        - port: 6379
  policyTypes:
    - Ingress
