---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frigate-prod-tls
  namespace: apps
spec:
  secretName: frigate-prod-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - frigate.$SERVICES_DOMAIN
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: frigate-ingress
  namespace: apps
spec:
  entryPoints:
    - websecure
    - websecure-proxy
  routes:
    - match: Host(`frigate.$SERVICES_DOMAIN`)
      kind: Rule
      middlewares:
        - name: geoblock
          namespace: base
        - name: crowdsec-bouncer
          namespace: base
        - name: forwardauth-authelia
          namespace: base
      services:
        - name: frigate
          port: 8971
  tls:
    secretName: frigate-prod-tls
