---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-media-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: frigate-media
    volumeAttributes:
      server: nfs-server.base.svc.cluster.local
      share: /frigate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs
  volumeName: frigate-media-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config-pvc
  namespace: apps
  labels:
    auto-backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
