apiVersion: apps/v1
kind: Deployment
metadata:
  name: freshrss
  namespace: apps
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: freshrss
  template:
    metadata:
      labels:
        app: freshrss
    spec:
      containers:
        - name: freshrss
          image: freshrss/freshrss:1.29.1
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 80
          readinessProbe:
            tcpSocket:
              port: 80
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
            initialDelaySeconds: 10
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 128Mi
          env:
            - name: TZ
              value: "America/New_York"
            - name: CRON_MIN
              value: "2,32"
            - name: FRESHRSS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: freshrss-user-credentials
                  key: password
            - name: FRESHRSS_ENV
              value: "production"
            - name: TRUSTED_PROXIES
              value: "10.42.0.0/16, 10.43.0.0/16"
            - name: FRESHRSS_INSTALL
              value: |-
                --api-enabled
                --base-url https://rss.$SERVICES_DOMAIN
                --default-user admin
                --language en
            - name: FRESHRSS_USER
              value: |-
                --api-password \$FRESHRSS_PASSWORD
                --email $DOMAIN_OWNER_EMAIL
                --language en
                --password \$FRESHRSS_PASSWORD
                --user admin
          volumeMounts:
            - name: freshrss-data
              mountPath: /var/www/FreshRSS/data
            - name: freshrss-extensions
              mountPath: /var/www/FreshRSS/extensions
      volumes:
        - name: freshrss-data
          persistentVolumeClaim:
            claimName: freshrss-data-pvc
        - name: freshrss-extensions
          persistentVolumeClaim:
            claimName: freshrss-extensions-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: freshrss
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: freshrss
  ports:
    - port: 80
      targetPort: 80
