apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-data-pvc
  namespace: apps
  labels:
    auto-backup: "true"
spec:
  storageClassName: mayastor-install-single-replica
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-extensions-pvc
  namespace: apps
  labels:
    auto-backup: "true"
spec:
  storageClassName: mayastor-install-single-replica
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: freshrss-user-credentials
  namespace: apps
type: Opaque
stringData:
  password: "$FRESHRSS_PASSWORD"

