apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-data-pvc
  namespace: apps
spec:
  storageClassName: openebs-single-replica
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-extensions-pvc
  namespace: apps
spec:
  storageClassName: openebs-single-replica
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

